env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
